service: expressInAWSArticles #Name of your App

provider:
 name: aws
 runtime: nodejs10.x # Node JS version
 memorySize: 512
 timeout: 15
 stage: production
 region: eu-west-3 # AWS region

functions:
 api:
   handler: lambda.handler
   events:
     - http: ANY {proxy+}
     - http: ANY /